Yannick Jacquet is a projection mapping artist whose background is in graphic design. He is one of the founders of the small projection mapping group AntiVJ. In that group of artists, each person has a different specific skill (whether it be the concept, creating content to map with, figuring out calculations and technical things, or audio) Depending on the project, Yannick’s job mostly consists of the actual mapping part of the process, but sometimes helps with conceptualization as well. An example of a project that he worked on with AntiVJ is called “St Gervais,” and is a permanent projection installation inside of a building in Geneva, Switzerland.
Artist Website: http://www.legoman.net/
St Gervais: http://www.antivj.com/st_gervais/

Lauren McCarthy is a new media artist and programmer. In her work, she focuses on topics like identity and anonymity, surveillance and privacy, and mediated performance. She commonly uses software as a medium instead of just a tool. She has said that she is never trying to necessarily solve a specific problem, but rather work toward a thematic direction and see what happens along the way. With that said, she is very interested in social interactions, possibly because she does not consider herself to be good at interaction, so she builds apps and devices that are designed to be tools to encourage interacting in nonconventional ways. Besides pplkpr, an example of this is a device called the “happiness hat” that forces the wearer to keep smiling in order to avoid physical pain. This project is pretty humorous. satirical, and not really meant to be marketed, but was inspired by those who are not good at interacting and making friends that might have an easier time if they smiled more often.
Artist Website: http://lauren-mccarthy.com/
happiness hat: https://vimeo.com/7283341


Kyle McDonald is also a new media artist who works with Lauren McCarthy in a lot of his work. Their work has similarities in some ways, but he (as well as she) has his own sets of skills that are prominent both in their collaborations and in his separate projects. Topics of focus for McDonald include big data aggregation, applications, and immersive experiences. Like Lauren, it is common for him to use software as the medium. One example of this is an app that they developed together called pplkpr (“people keeper”). This app keeps track of all the different relationships that the user has, and algorithmically calculates which relationships are positive ones, and which are negative ones. Kyle has done a lot of collaborative work, which has resulted in him having a very wide range of different types of projects using lots of different mediums. He has worked in projection mapping, computer vision, and hacking and coding.
Artist Website: http://kylemcdonald.net/
pplkpr: https://vimeo.com/116025182 and https://vimeo.com/116957464